# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6296e5d863032aeee30e0c7473b8728ab89c4738a3bee55a2bc39a61904cf21798357387eb08315996a291a3eeeeb02c5854f875ada7fa2127b12842c7b1e52b

test:
  secret_key_base: 9f390021ae44cf36c224734efb931be6adceb9dbb8623dacb01445a43d68c48e32063735d7121cb8d911b5ad27a35480768570d05c40d237530051409e10bd76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
